### ISSUE TITLE
it's doesn't work!

### ISSUE THREAD

**Issue by sinahosseini76** [martinnaj/YouTubeDLAPI#1]
hi man h just get "Please provide valid ID." !!
i really need your  code bro :(
are you test it ?
could you please fix it thanks

**Comment by martinnaj** [comment]
Hi, yeah, just send a get request to:

https://najemi.cz/ytdl/handler.php?url=https://www.youtube.com/watch?v=CcCw1ggftuQ

Replace the URL with the URL of the video you wish to download :)
